### ISSUE TITLE
[New Rule] Legal Entity Identification 

### ISSUE THREAD

**Issue by sambacha** [sider/goodcheck-rules#42]
Legal Entity and Trade Name is a great use-case for goodcheck, and we are using it in our new documentation generation usage. 

Example:

```markdown
rules:
  - id: com.example.freighttrust
    pattern: Freight Trust
    message: |
      FreightTrust Corproation

      Did you mean the legal entity?
    justification:
      - When you mean the Legal Entity
      - The C Corporation
    glob:
      - app/views/**/*.html.slim
      - config/locales/**/*.yaml
    pass:
      - <a>FreightTrust Corporation</a>
    fail:
      - <a>Freight Trust Corporation</a>
```

You can read more about LEI at this [Bloomberg link ](https://lei.bloomberg.com/) 

To find out more about the usage of [LEI](https://lmgtfy.com/?q=MiFi+Eu+lei) and [EU MiFID Compliance here](https://www.esma.europa.eu/policy-rules/mifid-ii-and-mifir)

**Comment by ybiquitous** [comment]
Thanks for your report. Sounds good. 👍 
If I add a new file `rules/legal-entity.yml`, does it satisfy your need?

```yaml
- id: review.sider.freighttrust
  pattern: "Freight Trust"
  message: Did you mean "FreightTrust"?
  pass: FreightTrust  
```
